# Generated by Django 3.2 on 2021-12-28 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'get_latest_by': ['-created'], 'ordering': ['-created'], 'verbose_name_plural': 'messages'},
        ),
    ]
