# Generated by Django 3.2 on 2021-12-28 17:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('message', '0002_alter_message_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'get_latest_by': ['created'], 'ordering': ['created'], 'verbose_name_plural': 'messages'},
        ),
        migrations.RemoveField(
            model_name='message',
            name='apply',
        ),
        migrations.RemoveField(
            model_name='message',
            name='parent',
        ),
        migrations.AddField(
            model_name='message',
            name='is_readed',
            field=models.BooleanField(default=False, verbose_name='message lu'),
        ),
        migrations.AlterField(
            model_name='message',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='auteur'),
        ),
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.TextField(help_text='message', verbose_name='message'),
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('D', 'Dialogue'), ('C', 'Chat')], default='D', max_length=1, verbose_name='type de chat')),
                ('members', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Membres')),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='chat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='message.chat', verbose_name='chat'),
        ),
    ]
