# Generated by Django 3.2 on 2021-12-29 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=30, verbose_name='name')),
                ('email', models.EmailField(max_length=254, verbose_name='your email')),
                ('phone', models.CharField(max_length=40, verbose_name='phone')),
                ('subject', models.CharField(max_length=60, verbose_name='your subject')),
                ('message', models.TextField(max_length=100, verbose_name='your message')),
            ],
            options={
                'ordering': ['-created'],
                'abstract': False,
            },
        ),
    ]
