# Generated by Django 3.2.9 on 2021-12-24 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='add title for article', max_length=255, verbose_name='title')),
                ('subtitle', models.CharField(blank=True, help_text='add subtitle for article', max_length=255, verbose_name='subtitle')),
                ('body', models.TextField(verbose_name='content')),
                ('image', models.ImageField(upload_to='blog/', verbose_name='post cover')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='slug')),
                ('published', models.BooleanField(default=False, verbose_name='published')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='keywords')),
            ],
            options={
                'verbose_name_plural': 'blog',
                'ordering': ['-created'],
                'get_latest_by': ['-created'],
            },
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['id'], name='blog_post_id_faf3eb_idx'),
        ),
    ]
