# Generated by Django 3.2.9 on 2021-12-10 10:18

import django.core.validators
from django.db import migrations, models
import utils.func_utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='define your project name.', max_length=180, null=True, verbose_name='project name')),
                ('budget', models.DecimalField(decimal_places=2, help_text='define the budget for financing your project.', max_digits=12, verbose_name='project budget')),
                ('resume', models.TextField(help_text='make an overall summary of your project', max_length=250, null=True, verbose_name='project summary')),
                ('description', models.TextField(help_text='make an overall summary of your project', null=True, verbose_name='project description')),
                ('logo', models.ImageField(blank=True, null=True, upload_to=utils.func_utils.save_project_file, verbose_name='project logo')),
                ('video', models.URLField(blank=True, default='https://example.com/URLG5433', null=True)),
                ('document', models.FileField(blank=True, null=True, upload_to=utils.func_utils.save_project_file, validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('is_published', models.BooleanField(default=False, verbose_name='published')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
