# Generated by Django 3.2.9 on 2021-12-22 19:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20211222_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='projects/docs/%Y/%m%d', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.AlterField(
            model_name='project',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='projects/logo/%Y/%m%d', verbose_name='project logo'),
        ),
    ]
