# Generated by Django 3.2.9 on 2021-12-10 10:18

from django.db import migrations, models
import django.utils.timezone
import utils.func_utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('job', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=60, null=True, unique=True)),
                ('title', models.CharField(blank=True, max_length=120, null=True)),
                ('address', models.CharField(blank=True, max_length=120, null=True)),
                ('experince', models.CharField(blank=True, choices=[('-1', "Moins d'une année"), ('1-3', '1-3 ans'), ('3-5', '3-5 ans'), ('5-10', '5-10 ans'), ('+10', 'Plus de 10 ans')], max_length=60, null=True)),
                ('description', models.TextField(blank=True, help_text='Write your biography in 300 words.', max_length=300, null=True, verbose_name='user description')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=utils.func_utils.save_avatar_file, verbose_name='user avatar')),
                ('is_investor', models.BooleanField(default=False, help_text='Are you an investor ?', verbose_name='investor')),
                ('is_project_owner', models.BooleanField(default=False, help_text='Are you a project owner ?', verbose_name='project owner')),
                ('is_job_seeker', models.BooleanField(default=False, help_text='Are you a job seeker ?', verbose_name='job seeker')),
                ('is_company', models.BooleanField(default=False, help_text='Are you a company ?', verbose_name='company')),
                ('company', models.CharField(max_length=180, null=True, verbose_name='comapny name')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('skills', models.ManyToManyField(to='job.Skills')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ['-date_joined'],
            },
        ),
    ]
