# Generated by Django 3.2.9 on 2021-12-21 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20211216_1032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_company',
            new_name='is_recruiter',
        ),
    ]
