# dash.urls.py

from django.urls import path, include

from message import views as msg_views
from dash.views import recruiter, shared, job_seeker, project_owner, investor, staff

app_name = "dashboard"
urlpatterns = [
    path("", shared.dashboard_view, name="dashboard"),
    
    # url recruiter
    path('recruiter/',
        include(
            [
                path(route="", view=recruiter.dashboard, name="recruiter_dashboard"),
                path(
                    route="offers/",
                    view=recruiter.offer_list_view,
                    name="recruiter_list_offer"
                ),
                path(
                    route="offer/create/", 
                    view=recruiter.offer_create_view,
                    name="recruiter_create_offer"
                ),
                path(
                    route="offer/<pk>/update/",
                    view=recruiter.offer_update_view,
                    name="recruiter_update_offer"
                ),
                path(
                    route="offer/<pk>/delete/",
                    view=recruiter.offer_delete_view,
                    name="recruiter_delete_offer"
                ),
                path(
                    route="offer/candidates/",
                    view=recruiter.offer_candidate_list_view,
                    name="recruiter_candidate_apply"
                ),
                path(
                    route="offer/candidate/<slug>/detail/",
                    view=recruiter.offer_candidate_list_view,
                    name="recruiter_candidate_detail"
                ),
                path(
                    route="offer/applies/list/",
                    view=recruiter.candidate_per_offer,
                    name="recruiter_candidate_per_offer"
                ),
                path(
                    route="messages/",
                    view=msg_views.dialogue_view,
                    name="recruiter_dialogue"
                ),
                path(
                    route="message/create/<user_id>/",
                    view=msg_views.create_dialogue_view,
                    name="recruiter_create_dialogue"
                ),
                path(
                    route="message/<chat_id>/",
                    view=msg_views.message_view,
                    name="recruiter_messages"
                ),
                path(
                    route="settings/",
                    view=recruiter.settings,
                    name="recruiter_settings"
                ),
            ]
        )
    ),
    path(
        "recruiter/",
        include(
            [
                path(route="", view=recruiter.dashboard, name="recruiter_dashboard"),
                path(
                    route="offers/",
                    view=recruiter.offer_list_view,
                    name="recruiter_list_offer",
                ),
                path(
                    route="offer/create/",
                    view=recruiter.offer_create_view,
                    name="recruiter_create_offer",
                ),
                path(
                    route="offer/<pk>/update/",
                    view=recruiter.offer_update_view,
                    name="recruiter_update_offer",
                ),
                path(
                    route="offer/<pk>/delete/",
                    view=recruiter.offer_delete_view,
                    name="recruiter_delete_offer",
                ),
                path(
                    route="offer/candidates/",
                    view=recruiter.offer_candidate_list_view,
                    name="recruiter_candidate_apply",
                ),
                path(
                    route="offer/candidate/<slug>/detail/",
                    view=recruiter.offer_candidate_list_view,
                    name="recruiter_candidate_detail",
                ),
                path(
                    route="offer/applies/list/",
                    view=recruiter.candidate_per_offer,
                    name="recruiter_candidate_per_offer",
                ),
                path(
                    route="settings/",
                    view=recruiter.settings,
                    name="recruiter_settings",
                ),
            ]
        ),
    ),
    # url project-owner
    path(
        "project-owner/",
        include(
            [
                path(
                    route="",
                    view=project_owner.dashboard,
                    name="project_owner_dashboard",
                ),
                path(
                    route="profile/",
                    view=project_owner.Project_OwnerView.as_view(),
                    name="project_owner_profile",
                ),
                path(
                    route="create/project/",
                    view=project_owner.ProjectCreateView.as_view(),
                    name="project_owner_create_project",
                ),
                path(
                    route="projects/",
                    view=project_owner.ProjectListView.as_view(),
                    name="project_owner_list_project",
                ),
                path(
                    route="project/<pk>/update",
                    view=project_owner.ProjectUpdateView.as_view(),
                    name="project_owner_update_project",
                ),
                path(
                    route="project/<pk>/delete/",
                    view=project_owner.ProjectDeleteView.as_view(),
                    name="project_owner_delete_project",
                ),
                path(
                    route="dashboard/",
                    view=project_owner.DashView.as_view(),
                    name="project_owner_dash_view",
                ),
                path(
                    route="<slug:slug>/detail/",
                    view=project_owner.ProjectDetailView.as_view(),
                    name="project_owner_detail",
                ),
            ]
        ),
    ),
    # url job_seeker
    path(
        "job-seeker",
        include(
            [
                path(route="", view=job_seeker.dashboard, name="job_seeker_dashboard"),
                path(
                    route="offers/",
                    view=job_seeker.OfferList.as_view(),
                    name="job_seeker_offers_list",
                ),
                path(
                    route="<slug:slug>/detail/",
                    view=job_seeker.OfferDetail.as_view(),
                    name="job_seeker_offers_details",
                ),
                path(
                    route="offres/postuler/",
                    view=job_seeker.OfferApplyListView.as_view(),
                    name="job_seeker_offres_postuler",
                ),
                path(route="resume/", view=job_seeker.user_resume, name="view-resume"),
                path(
                    route="kpi/",
                    view=job_seeker.KpiView.as_view(),
                    name="job_seeker_kpi",
                ),
            ]
        ),
    ),
    # url investor
    path(
        "investor/",
        include(
            [
                path(route="", view=investor.dashboard, name="investor_dashboard"),
                path(
                    route="dashboard/",
                    view=investor.DashView.as_view(),
                    name="investor_dash_view",
                ),
                path(
                    route="favorite/",
                    view=investor.favorite_ajax,
                    name="project_favorite",
                ),
                path(
                    route="followed-project/",
                    view=investor.followed_project,
                    name="followed_project",
                ),
            ]
        ),
    ),
    # url staff
    path(
        "staff/",
        include(
            [
                path(route="dashboard/", view=staff.dashboard, name="staff"),
                path(route="settings/", view=staff.settings, name="staff_settings"),
                path(
                    route="candidates/",
                    view=staff.CandidateListView.as_view(),
                    name="staff_candidates",
                ),
                path(
                    route="recruiters/",
                    view=staff.RecruiterListView.as_view(),
                    name="staff_recruiters",
                ),
                path(
                    route="investors/",
                    view=staff.InvestorListView.as_view(),
                    name="staff_investors",
                ),
                path(
                    route="project-owners/",
                    view=staff.ProjectOwnerListView.as_view(),
                    name="staff_project_owners",
                ),
            ]
        ),
    ),
]
