# Generated by Django 3.2.9 on 2021-12-10 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Seen', 'Vue'), ('Rejected', 'Rejeté'), ('Accepted', 'Accepté')], max_length=30, null=True)),
            ],
            options={
                'verbose_name_plural': 'Applies',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=180, unique=True, verbose_name='category title')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='certificate name')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='certificate description')),
                ('issuer', models.CharField(blank=True, max_length=200, null=True, verbose_name='certificate issuer name')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='certificate issue date')),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name='expiration date')),
                ('url', models.URLField(blank=True, null=True, verbose_name='certificate url')),
                ('is_active', models.BooleanField(default=True, verbose_name='certificate is active')),
            ],
            options={
                'ordering': ['-created'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, null=True, verbose_name='title')),
                ('subtitle', models.CharField(max_length=200, null=True, verbose_name='sub-title')),
                ('description', models.TextField(verbose_name='description')),
                ('project_url', models.URLField(blank=True, default='https://www.myproject.com/', max_length=250, null=True, verbose_name='project url')),
                ('begin_date', models.DateField(blank=True, null=True, verbose_name='begin date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='begin end')),
            ],
            options={
                'ordering': ['-created'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=180, unique=True, verbose_name='Skills title')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Skills',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=180, null=True, verbose_name='title')),
                ('content', models.TextField(null=True, verbose_name='content')),
                ('document_desc', models.FileField(blank=True, null=True, upload_to='career/', verbose_name='document')),
                ('date_validation', models.DateTimeField(verbose_name='deadline')),
                ('offer_type', models.CharField(choices=[('Freelance', 'Freelance'), ('Full-Time', 'Full-Time'), ('Part-Time', 'Part-Time')], default='Freelance', max_length=180, null=True, verbose_name='offer type')),
                ('education_level', models.CharField(choices=[('Bac', 'Bac'), ('Bac+2', 'Bac+2'), ('Licene', 'Licene'), ('Master', 'Master'), ('All', 'Tous les niveaux')], default='Bac', max_length=180, null=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='job.category', verbose_name='category')),
            ],
            options={
                'ordering': ['-created'],
                'abstract': False,
            },
        ),
    ]
