# Generated by Django 3.2 on 2021-12-13 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_alter_experience_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name="publier l'offre"),
        ),
    ]
