# Generated by Django 3.2 on 2021-12-13 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_offer_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='category title'),
        ),
    ]
