# Generated by Django 3.2 on 2021-12-13 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_alter_category_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(default=1, max_length=180, verbose_name='category title'),
            preserve_default=False,
        ),
    ]
