# Generated by Django 3.2 on 2021-12-13 18:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job', '0006_alter_category_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='candidate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='candidats'),
        ),
        migrations.AlterField(
            model_name='apply',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.offer', verbose_name='offers'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(choices=[('digital', 'Digital & Creative'), ('sales', 'Sales & Marketing'), ('marketing', 'Marketing & PR'), ('contractor', 'IT Contractor'), ('others', 'Others Job')], max_length=10, verbose_name='category title'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='job.category', verbose_name="catégorie d'emploi"),
        ),
        migrations.AlterField(
            model_name='offer',
            name='content',
            field=models.TextField(null=True, verbose_name="description de l'emploi"),
        ),
        migrations.AlterField(
            model_name='offer',
            name='education_level',
            field=models.CharField(choices=[('Bac', 'Bac'), ('Bac+2', 'Bac+2'), ('Licene', 'Licene'), ('Master', 'Master'), ('All', 'Tous les niveaux')], default='Bac', max_length=180, null=True, verbose_name='qualification du poste'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='offer_type',
            field=models.CharField(choices=[('Freelance', 'Freelance'), ('Full-Time', 'Full-Time'), ('Part-Time', 'Part-Time')], default='Freelance', max_length=180, null=True, verbose_name="type d'offre"),
        ),
        migrations.AlterField(
            model_name='offer',
            name='title',
            field=models.CharField(max_length=180, null=True, verbose_name="Intitulé de l'emploi"),
        ),
    ]
