# Generated by Django 3.2.9 on 2021-12-16 10:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job', '0008_alter_category_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='candidate',
            field=models.ForeignKey(limit_choices_to={'is_active': True, 'is_job_seeker': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='candidats'),
        ),
    ]
