# Generated by Django 3.2.9 on 2021-12-24 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0012_alter_apply_candidate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apply',
            options={'ordering': ['-created'], 'verbose_name_plural': 'Candidatures'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': "Catégories d'emploi"},
        ),
        migrations.AlterModelOptions(
            name='offer',
            options={'ordering': ['-created'], 'verbose_name_plural': "Offres d'emplois"},
        ),
    ]
