# Generated by Django 4.0.6 on 2022-08-30 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0013_auto_20211224_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='category',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='offer_type',
        ),
        migrations.AlterField(
            model_name='offer',
            name='education_level',
            field=models.CharField(choices=[('L1-GI', 'L1-GI'), ('L2-GI', 'L2-GI'), ('L3-GI', 'L3-GI')], default='Bac', max_length=180, null=True, verbose_name='qualification du poste'),
        ),
    ]
