# Generated by Django 4.0.6 on 2022-08-30 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0014_remove_offer_category_remove_offer_offer_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='offer_type',
            field=models.CharField(choices=[('Examen', 'Examen'), ('Devoir', 'Devoir')], default='Freelance', max_length=180, null=True, verbose_name="type d'offre"),
        ),
        migrations.AlterField(
            model_name='offer',
            name='content',
            field=models.TextField(null=True, verbose_name='donner une description'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='date_validation',
            field=models.DateTimeField(verbose_name='Date limite'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='education_level',
            field=models.CharField(choices=[('L1-GI', 'L1-GI'), ('L2-GI', 'L2-GI'), ('L3-GI', 'L3-GI')], default='L1-GI', max_length=180, null=True, verbose_name='Classe'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='publier'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='title',
            field=models.CharField(max_length=180, null=True, verbose_name='Donner un titre'),
        ),
    ]
