# Generated by Django 4.0.6 on 2022-08-30 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0015_offer_offer_type_alter_offer_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='offer_type',
            field=models.CharField(choices=[('Examen', 'Examen'), ('Devoir', 'Devoir')], default='Examen', max_length=180, null=True, verbose_name="type d'offre"),
        ),
    ]
